# Generated by Django 4.0.4 on 2022-12-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='loaction',
            new_name='location',
        ),
    ]
