# Generated by Django 4.0.4 on 2023-01-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rename_loaction_houses_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='url',
            field=models.TextField(max_length=100000),
        ),
    ]
