# Generated by Django 4.0.4 on 2022-12-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_hashouses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hasHouses',
            new_name='has_houses',
        ),
    ]
