# Generated by Django 4.0.4 on 2022-12-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_hashouses_user_has_houses'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='has_houses',
            field=models.BooleanField(default=False),
        ),
    ]
